language: c
# Compiler is irrelevant, we'll be using one
# that Travis doesn't provide by default.
compiler: gcc
before_install:
 - export ARTIFACTS=$(pwd)
 - cd ../
 - export ARM_EABI=$(pwd)
# Install binutils
 - sudo wget http://ftp.gnu.org/gnu/binutils/binutils-2.24.tar.bz2
 - bzip2 -dc binutils-2.24.tar.bz2 | tar -xf -
 - sudo mkdir build-binutils
 - cd build-binutils
 - sudo ../binutils-2.24/configure --target=arm-none-eabi --prefix=/opt/gnuarm
 - sudo make -j 8 all
 - sudo make install
# Install GCC
 - wget http://ftp.gnu.org/gnu/gcc/gcc-4.8.3/gcc-4.8.3.tar.bz2
 - bzip2 -dc gcc-4.8.3.tar.bz2 | tar -xf -
 - mkdir ../build-gcc
 - cd ../build-gcc
 - ../gcc-4.8.3/configure --target=arm-none-eabi --prefix=/opt/gnuarm --without-headers --with-newlib  --with-gnu-as --with-gnu-ld --enable-languages='c'
 - make -j 8 all-gcc
 - make install-gcc
install:
 - cd $ARM_EABI
 - wget http://www.cl.cam.ac.uk/freshers/raspberrypi/tutorials/os/downloads/arm-none-eabi.tar.bz2
 - tar xjvf arm-none-eabi.tar.bz2
 - export PATH=$PATH:$ARM_EABI/arm2008q3/bin
 - cd $ARTIFACTS
script: make