language: python
# Compiler is irrelevant, we'll be using one
# that Travis doesn't provide by default.
python: 
 - "2.7"
before_install:
 - export ARTIFACTS=$(pwd)
 - cd ../
 - export ARM_EABI=$(pwd)
 - sudo apt-get update
 - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
install:
 - cd $ARM_EABI
 - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded --yes
 - sudo apt-get update
 - sudo apt-get install gcc-arm-none-eabi
 - cd ~
 - sudo pip install pillow -U
 - cd $ARTIFACTS
script: make